---
spring:
  profiles:
    active: es

---

spring:
  profiles: es

db:
  username: YML Spanish User Name
  password: YML Spanish Password
  url: YML Spanish DB URL

jms:
  username: YML Spanish JMS User Name
  password: YML Spanish JMS Password
  url: YML Spanish JMS URL

